services:
  filament-calculator:
    build:
      context: https://github.com/Chr1s16/filament-calculator.git#main
      dockerfile: Dockerfile
    ports:
      - "5151:80"
    restart: unless-stopped
